variables:
  COMMAND_NAME:
    type: string
    required: true
  TARGET:
    type: string
    required: false
  ATTACH_REGEX:
    type: string
    required: false
  AUTHOR_EMAIL:
    type: string
    required: false
  AUTHOR_NAME:
    type: string
    required: false
  AUTHOR_PHONE:
    type: string
    required: false
  COMPONENTS:
    type: string
    required: false
  COMPRESS:
    type: boolean
    required: false
  FORCE:
    type: boolean
    required: false
  FORMAT:
    type: string
    required: false
  PACKAGE_EXCLUDE_TYPE:
    type: string
    required: false
  PACKAGE_GROUP:
    type: string
    required: false
  PACKAGE_TYPE:
    type: string
    required: false
  SUPPLIER_EMAIL:
    type: string
    required: false
  SUPPLIER_NAME:
    type: string
    required: false
  SUPPLIER_PHONE:
    type: string
    required: false
  SUPPLIER_URL:
    type: string
    required: false
  APP_NAME:
    type: string
    required: false
  APP_VERSION:
    type: string
    required: false
  ATTEST_CONFIG:
    type: string
    required: false
  ATTEST_DEFAULT:
    type: string
    required: false
  BACKOFF:
    type: string
    required: false
  CACHE_ENABLE:
    type: boolean
    required: false
  CONFIG:
    type: string
    required: false
  CONTEXT_DIR:
    type: string
    required: false
  ENV:
    type: string
    required: false
  FILTER_REGEX:
    type: string
    required: false
  FILTER_SCOPE:
    type: string
    required: false
  GIT_BRANCH:
    type: string
    required: false
  GIT_COMMIT:
    type: string
    required: false
  GIT_TAG:
    type: string
    required: false
  LABEL:
    type: string
    required: false
  LEVEL:
    type: string
    required: false
  OCI:
    type: boolean
    required: false
  OCI_REPO:
    type: string
    required: false
  OUTPUT_DIRECTORY:
    type: string
    required: false
  OUTPUT_FILE:
    type: string
    required: false
  PIPELINE_NAME:
    type: string
    required: false
  PREDICATE_TYPE:
    type: string
    required: false
  PRODUCT_KEY:
    type: string
    required: false
  PRODUCT_VERSION:
    type: string
    required: false
  SCRIBE_AUTH_AUDIENCE:
    type: string
    required: false
  SCRIBE_CLIENT_ID:
    type: string
    required: false
  SCRIBE_CLIENT_SECRET:
    type: string
    required: false
  SCRIBE_ENABLE:
    type: boolean
    required: false
  SCRIBE_LOGIN_URL:
    type: string
    required: false
  SCRIBE_URL:
    type: string
    required: false
  STRUCTURED:
    type: boolean
    required: false
  TIMEOUT:
    type: string
    required: false
  VERBOSE:
    type: integer
    required: false
  COLUMNS:
    type: string
    required: false
  CURRENT:
    type: boolean
    required: false
  FILTERS:
    type: string
    required: false
  ALL_ENV:
    type: boolean
    required: false
  BUILD_TYPE:
    type: string
    required: false
  BUILDER_ID:
    type: string
    required: false
  EXTERNAL:
    type: string
    required: false
  FINISHED_ON:
    type: string
    required: false
  INVOCATION:
    type: string
    required: false
  PREDICATE:
    type: string
    required: false
  STARTED_ON:
    type: string
    required: false
  STATEMENT:
    type: string
    required: false
  ATTESTATION:
    type: string
    required: false
  COMMON_NAME:
    type: string
    required: false
  EMAIL:
    type: string
    required: false
  INPUT_FORMAT:
    type: string
    required: false
  URI:
    type: string
    required: false
